### ISSUE TITLE
Very good example!  Where are the embeddings created, CPU or LPU?

### ISSUE THREAD

**Issue by aurotripathy** [Debapriya-source/nyaya-gpt#1]
Grateful if you could answer this question?
<code>
embeddings_model = HuggingFaceEmbeddings(
        model_name="sentence-transformers/all-mpnet-base-v2")
</code>

<code>
db = FAISS.load_local("db/faiss_index_constitution",
                              embeddings_model, allow_dangerous_deserialization=True)
</code>

Can they be created on the LPU?

Thank you!

**Comment by Debapriya-source** [comment]
# Where are the embeddings created, CPU or LPU?
The creation and storing of embeddings are computed on the CPU.

# Can they be created on the LPU?
Although it should be possible to implement this with LPU in future, currently we don't have access to this kind of hardware for development purpose. We can only utilize the fast LPU inference through Groq's API service at this time.

I hope that answers your question.
